[attributes]
# Base strength of the character (uncomment to enable)
# STR = 10

# Whether the character is visible on the map
visible = true

# Radius of the character's collision circle
radius = 0.5

# Number of item slots available in the character's inventory
inventory_slots = 8
