[ui]
# The role of the widget, currently "game" or "button"
role = "button"
# The action to send to the server when clicked
# See https://eldiron.com/scripting_data/index.html#available-actions
action = "none"
