[workspace]

members = [
    "core_server",
    "core_render",
    "core_embed_binaries",
    "creator",
    "client_standalone",
    "client_standalone_web",
    "run-wasm"
]

#edition = "2021"
resolver = "2"