[package]
name = "eldiron"
version = "0.1.0"
edition = "2021"
authors = ["Markus Moenig"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
server = { path = "server" }
env_logger = "0.9"
log = "0.4"
pixels = "0.9.0"
winit = "0.26"
winit_input_helper = "0.11"
png = "0.17.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusttype = "0.9.2"
vectorize = "0.2.0"
itertools = "0.10.2"
zeno = "0.2.1"
rand = "0.8.5"
pathfinding = "3.0.11"
#rhai = "*"
rhai = { git = "https://github.com/rhaiscript/rhai/" }
