[workspace]

members = ["creator", "run-wasm", "shared", "clients/solo"]
resolver = "2"

[workspace.dependencies]
theframework = { version = "0.1.40", git = "https://github.com/markusmoenig/TheFramework", features = [
    "ui",
], default-features = true }
# theframework = { path = "../TheFramework", features = [
#     "ui",
# ], default-features = true }

rusterix = { version = "0.2.8", git = "https://github.com/markusmoenig/Rusterix" }
# rusterix = { path = "../Rusterix" }

[workspace.package]
edition = "2024"
version = "0.8.40"
license = "MIT"
authors = ["Markus Moenig"]
description = "A game creator for classical RPGs."

[patch.crates-io]
radium = { version = "1.1.0", git = "https://github.com/youknowone/ferrilab", branch = "fix-nightly" }
