[workspace]

members = [
    "core_server",
    "core_render",
    "core_embed_binaries",
    "creator_lib",
    "creator_main",
    "client_standalone",
#    "client_standalone_web",
#    "run-wasm",
    "server",
    "client",
#    "client_web"
]

#edition = "2021"
resolver = "2"