[package]
name = "creator"
version = "0.5.5"
edition = "2021"
authors = ["Markus Moenig"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_server = { path = "../core_server", features = ["data_editing"] }
core_shared = { path = "../core_shared" }
core_render = { path = "../core_render" }
env_logger = "0.9"
log = "0.4"
pixels = "0.9.0"
winit = "0.26"
winit_input_helper = "0.12"
png = "0.17.5"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
fontdue = "0.7.2"
vectorize = "0.2.0"
itertools = "0.10.2"
zeno = "0.2.1"
rand = "0.8.5"
pathfinding = "3.0.11"
rhai = { version = "*", default-features = true, features = ["only_i32", "f32_float"] }
#rhai = { git = "https://github.com/rhaiscript/rhai/" }
regex = "1.5"
directories = "4.0"
fs_extra = "1.2.0"
open = "3.0.1"
copypasta = "0.8.1"
code_editor = "0.3.0"
rfd = "0.10.0"
audio-engine = "0.4.4"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde"
]