[package]
name = "creator"
version = "0.8.5"
edition = "2021"

[dependencies]
# theframework = { path = "../../TheFramework", features = ["ui", "code"]}
#theframework = { source = "https://github.com/markusmoenig/TheFramework", features = ["ui", "code"], default-features = true }
theframework = { version = "0.1.18", features = ["ui", "code"], default-features = true }
shared = { path = "../shared" }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorize = "0.2.0"
rust-embed = { version = "8", default-features = true, features = ["include-exclude"] }
png = "0.17"
open = "5.0.1"