[package]
name = "creator"
version = "0.8.5"
edition = "2021"
authors = ["Markus Moenig"]
description = "A game creator for retro RPGs."

[dependencies]
# theframework = { path = "../../TheFramework", features = ["ui", "code"]}
theframework = { git = "https://github.com/markusmoenig/TheFramework", features = ["ui", "code"], default-features = true }
# theframework = { version = "0.1.18", features = ["ui", "code"], default-features = true }
shared = { path = "../shared" }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorize = "0.2.0"
rust-embed = { version = "8", default-features = true, features = ["include-exclude"] }
png = "0.17"
open = "5.0.1"

[target.'cfg(not(target_os = "macos"))'.dependencies]
image_rs = { version = "0.24.6", package = "image" }

[package.metadata.bundle]
name = "Eldiron"
identifier = "com.moenig.eldiron"
icon = ["../build/Eldiron.icns"]
resources = ["../assets", "../game", "../resources"]
copyright = "Copyright (c) Markus Moenig 2023. All rights reserved."
category = "Game"
short_description = "A game creator for retro RPGs."
long_description = """
Create retro RPGs with Eldiron.
"""
