[package]
name = "creator"
version = "0.8.14"
edition = "2021"
authors = ["Markus Moenig"]
description = "A game creator for classical RPGs."

[[bin]]
name = "eldiron"
path = "src/main.rs"

[dependencies]
theframework = { git = "https://github.com/markusmoenig/TheFramework", features = [
    "ui",
    "code",
], default-features = true }
# theframework = { path = "../../TheFramework", features = [
#     "ui",
#     "code",
#     # "winit_app",
# ], default-features = true }
# theframework = { version = "0.1.20", features = [
#     "ui",
#     "code",
# ], default-features = true }
# forgedtiles = { path = "../../ForgedTiles/forgedtiles" }
forgedtiles = { git = "https://github.com/markusmoenig/ForgedTiles" }
shared = { path = "../shared" }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorize = "0.2.0"
rust-embed = { version = "8", default-features = true, features = [
    "include-exclude",
] }
rayon = "1"
png = "0.17"
open = "5.0.1"
fontdue = "0.8.0"
self_update = { version = "0.39.0", features = [
    "archive-tar",
    "compression-flate2",
] }
vek = { version = "0.17.1", default-features = true }
# rusterix = { path = "../../rusterix" }
rusterix = { git = "https://github.com/markusmoenig/Rusterix" }

[package.metadata.bundle]
name = "Eldiron"
identifier = "com.moenig.eldiron"
icon = ["../build/Eldiron.icns"]
resources = []
copyright = "Copyright (c) Markus Moenig 2024. All rights reserved."
category = "Game"
short_description = "A game creator for classical RPGs with modern features."
long_description = """
Create classical RPGs with Eldiron.
"""

# [lib]
# name = "rustapi"
# crate-type = ["staticlib"]

# vek = { version = "0.17", default-features = false, features = ["rgba"] }
# euc = { git = "https://github.com/zesterer/euc" }
