[package]
name = "shared"
version = "0.1.0"
edition = "2021"


[dependencies]
theframework = { version = "0.1.1", features = ["ui", "code"], default-features = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorize = "0.2.0"
