[package]
name = "shared"
version = "0.8.3"
edition = "2021"

[dependencies]
# theframework = { path = "../../TheFramework", features = ["ui", "code"]}
theframework = { version = "0.1.17", features = ["ui", "code"], default-features = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
vectorize = "0.2.0"
rayon = "1"
lazy_static = "1.4"
rand = "0.8.5"
