name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  linux_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          pkg-config --libs --cflags alsa
          sudo apt-get install libgtk-3-dev
          cd creator_main
          cargo build --verbose --release
          cd ..

      - name: Move Resources
        run: |
          mkdir build
          mv target/release/creator_main build/creator_main
          cp -r assets build
          cp -r game build
          cp -r resources build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: build

  windows_release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd creator_main
          cargo build --verbose --release
          cd ..

      - name: Move Resources
        run: |
          mkdir build
          mv target/release/creator_main.exe build/creator_main.exe
          cp -r assets build
          cp -r game build
          cp -r resources build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: build
