name: Rust

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        if: runner.os == "Linux"
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
          pkg-config --libs --cflags alsa
          sudo apt-get install libgtk-3-dev

      - name: Build
        run: |
          cd creator_main
          cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
